### ISSUE TITLE
could not find function "read_coverage_batch"

### ISSUE THREAD

**Issue by marce-sarrias** [jipingw/DegNorm#4]
Hello, 

For some reason I'm unable to run DegNorm (see error below). Any ideas?

Thank you,

Marcela

install.packages("remotes", repos = "http://cran.us.r-project.org")
remotes::install_github("jipingw/DegNorm")

## specify bam_files from RNA-seq, you should replace it by your own bam files
bam_file_list <- list.files("/path", pattern=".bam$", full.names=TRUE)

## gtf_file you used for RNA-seq alignment, replace it by your own gtf file
gtf_file <- "/path/myfile.gtf"

## calculate the read coverage score for all genes of all samples
coverage=read_coverage_batch(bam_file_list, gtf_file, cores=2)

## save the coverage results
save(coverage, file="coverage.Rda")

**Error in read_coverage_batch(bam_file_list, gtf_file, cores = 2) : 
  could not find function "read_coverage_batch"
Execution halted**

**Comment by jipingw** [comment]
Did you load the library by "library(DegNorm)"? 
read_coverage_batch is a function in the package.

**Comment by marce-sarrias** [comment]
Hello, 

Yes, small detail. This solved the problem!

Thank you and sorry!  

Marcela
